import React from 'react'

	const guests_list = [
		{
			episode: '001', 
			guest: 'Max & JazziCabbage',
			date: '12.14.23',
			topic: 'How gaming affects your life',
			social: 'https://twitter.com/JazziCabbage',
			other: '',
		},
		{ episode: '002', 
			guest: 'Mildra & Archangel',
			date:	'12.21.23',
			topic: 'Dissecting how we choose games',
			social: 'https://www.youtube.com/@MildraTheMonk671',
			other: '',
		},
		{ episode: '003',
			guest: 'Xanatrix Zedare & SupiJones',
			date: '12.28.23',
			topic: 'Explaining video games, TTRPGs',
			social: 'https://www.youtube.com/@MildraTheMonk671',
			other: '',
		},
		{ episode: '004', 
			guest: 'Bill Allan',
			date: '01.04.24',
			topic: 'D&D can change lives',
			social: 'https://twitter.com/TheBillAllan',
			other: '',
		},
		{ episode: '005', 
			guest: 'Jeff McNeil',
			date: '01.11.24',
			topic: 'Rule systems, and living abroad',
			social: 'https://twitter.com/geekygamerpod',
			other: '',
		},
		{ episode: '006', 
			guest: 'Mike Farmer',
			date: '01.18.24',
			topic: 'Life in a rock band',
			social: 'https://www.instagram.com/mikewritesandsings',
			other: 'https://mornoiz.bandcamp.com',
		},
		{ episode: '007', 
			guest: 'Lucas Duff',
			date: '01.25.24',
			topic: 'Gaming with mindfulness',
			social: 'https://www.youtube.com/@balladofthesevendice',
			other: '',
		},
		{ episode: '008',
			guest: 'Daniel Huffaker',
			date: '02.01.24',
			topic: 'Running extremely long Campaigns',
			social: 'https://twitter.com/geekygamerpod',
			other: '',
		},
		{ episode: '009',
			guest: 'Eric Holden',
			date: '02.08.24',
			topic: 'How to be a Game Master',
			social: 'https://www.youtube.com/@GoblinsCorner',
			other: 'https://twitter.com/goblinscorner',
		},
		{ episode: '010', 
			guest: 'Ken, Driz, and Bill',
			date: '02.15.24',
			topic: 'Life is hard, Discord is hard',
			social: 'https://twitter.com/geekygamerpod',
			other: '',
		},
		{ episode: '011', 
			guest: 'Claude Miles',
			date: '02.22.24',
			topic: 'Conspiracies and film-making',
			social: 'https://www.instagram.com/lordrevcolmiles/',
			other: '',
		},
		{ episode: '012', 
			guest: 'Shannon Lawrence',
			date: '02.29.24',
			topic: 'Horror and Sci-fi as genres',
			social: 'http://thewarriormuse.blogspot.com/',
			other: '',
		},
		{ episode: '013',
			guest: 'Juliet Rose',
			date: '03.07.24',
			topic: 'Writing stories from one\'s life',
			social: 'https://www.authorjulietrose.com/',
			other: 'https://twitter.com/julietrosewords',
		},
		{ episode: '014', 
			guest: 'Ken and Bill',
			date: '03.14.24',
			topic: 'Propaganda and getting Cancelled',
			social: 'https://twitter.com/geekygamerpod',
			other: '',
		},
		{ episode: '015', 
			guest: 'Jed Shaffer',
			date: '03.21.24',
			topic: 'The Generations of Gaming Consoles',
			social: 'https://lnns.co/EjwO-T5Xe6_',
			other: '',
		},
		{ episode: '016', 
			guest: 'Tawd Dorenfeld',
			date: '03.28.24',
			topic: 'Stop motion, A.I., and Andy Warhol',
			social: 'https://www.instagram.com/directordorenfeld/',
			other: '',
		},
		{ episode: '017', 
			guest: 'Ali Khamseh',
			date: '04.04.24',
			topic: 'Film-making in Iran',
			social: 'https://www.youtube.com/channel/UCP37QXeEcOQ5vJpQKgnph1w',
			other: '',
		},
		{ episode: '018', 
			guest: 'Danny Whitson',
			date: '04.11.24',
			topic: 'Comedy and Magic',
			social: 'https://dannywhitsonmagic.com',
			other: 'https://www.youtube.com/channel/UCfFPSTU5x2AOKvSU1_4y4XA',
		},
		{ episode: '019', 
			guest: 'Tyler Foley',
			date: '04.18.24',
			topic: 'Doing what you love',
			social: 'https://twitter.com/DropTheMicSTF',
			other: 'https://seantylerfoley.com',
		},
		{ episode: '020', 
			guest: 'Ben Rock',
			date: '04.19.24',
			topic: 'Co-creator of The Blair Witch Project',
			social:	'https://twitter.com/Neptunesalad',
			other: 'https://linktr.ee/neptunesalad',
		},
		{ episode: '021',
			guest: 'Lucas Zellers',
			date: '04.25.24',
			topic: 'Creating & gaming with a goal in mind',
			social: 'https://twitter.com/SparkOtter',
			other: 'https://scintilla.studio/',
		},
		{ episode: '022', 
			guest: 'Ken and Bill',
			date: '05.02.24',
			topic: 'Fallout Spoilers, D&D sucks, ST Tangirala BAILED',
			social: 'https://twitter.com/geekygamerpod',
			other: '',
		},
		{ episode: '023',  
			guest: 'JV Hilliard',
			date: '05.23.24',
			topic: 'The Warminster Series and Publishing',
			social: 'https://twitter.com/jvhilliardbooks',
			other: 'https://jvhilliard',
		},
	];

{/*
	for (let i = 0; i < guest_list.length; i++) {
		<li>Here</li>
	}
*/}
