import React from 'react'

function GuestInfo() {
	const guest_info = [
		{
			episode: '001', 
			guest: 'Max & JazziCabbage',
			link: 'https://youtu.be/0ZHThFAnk0I',
			date: '12.14.23',
			topic: 'How gaming affects your life',
			social: 'https://twitter.com/JazziCabbage',
			other: '',
		},
		{ episode: '002', 
			guest: 'Mildra & Archangel',
			link: 'https://youtu.be/jPUrLxi4lCQ',
			date:	'12.21.23',
			topic: 'Dissecting how we choose games',
			social: 'https://www.youtube.com/@MildraTheMonk671',
			other: '',
		},
		{ episode: '003',
			guest: 'Xanatrix Zedare & SupiJones',
			link: 'https://youtu.be/BFWLNCbmgd4',
			date: '12.28.23',
			topic: 'Explaining video games, TTRPGs',
			social: 'https://www.youtube.com/@MildraTheMonk671',
			other: '',
		},
		{ episode: '004', 
			guest: 'Bill Allan',
			link: 'https://youtu.be/EdxNzq-Eqws',
			date: '01.04.24',
			topic: 'D&D can change lives',
			social: 'https://twitter.com/TheBillAllan',
			other: '',
		},
		{ episode: '005', 
			guest: 'Jeff McNeil',
			link: 'https://youtu.be/wuUvjkh_2fQ',
			date: '01.11.24',
			topic: 'Rule systems, and living abroad',
			social: 'https://twitter.com/geekygamerpod',
			other: '',
		},
		{ episode: '006', 
			guest: 'Mike Farmer',
			link: 'https://youtu.be/THIYfZ_Vz10',
			date: '01.18.24',
			topic: 'Life in a rock band',
			social: 'https://www.instagram.com/mikewritesandsings',
			other: 'https://mornoiz.bandcamp.com',
		},
		{ episode: '007', 
			guest: 'Lucas Duff',
			link: 'https://youtu.be/D0Ff7kS6TCQ',
			date: '01.25.24',
			topic: 'Gaming with mindfulness',
			social: 'https://www.youtube.com/@balladofthesevendice',
			other: '',
		},
		{ episode: '008',
			guest: 'Daniel Huffaker',
			link: 'https://youtu.be/FGcbBno2T9I',
			date: '02.01.24',
			topic: 'Running extremely long Campaigns',
			social: 'https://twitter.com/geekygamerpod',
			other: '',
		},
		{ episode: '009',
			guest: 'Eric Holden',
			link: 'https://youtu.be/Q0oHE1sGpsE',
			date: '02.08.24',
			topic: 'How to be a Game Master',
			social: 'https://www.youtube.com/@GoblinsCorner',
			other: 'https://twitter.com/goblinscorner',
		},
		{ episode: '010', 
			guest: 'Ken, Driz, and Bill',
			link: 'https://youtu.be/ylYsqHHLDI4',
			date: '02.15.24',
			topic: 'Life is hard, Discord is hard',
			social: 'https://twitter.com/geekygamerpod',
			other: 'https://youtube.com/dreadloresystem',
		},
		{ episode: '011', 
			guest: 'Claude Miles',
			link: 'https://youtu.be/tsCbuQnpRvc',
			date: '02.22.24',
			topic: 'Conspiracies and film-making',
			social: 'https://www.instagram.com/lordrevcolmiles/',
			other: '',
		},
		{ episode: '012', 
			guest: 'Shannon Lawrence',
			link: 'https://youtu.be/O_qmRjJcu3Q',
			date: '02.29.24',
			topic: 'Horror and Sci-fi as genres',
			social: 'http://thewarriormuse.blogspot.com/',
			other: '',
		},
		{ episode: '013',
			guest: 'Juliet Rose',
			link: 'https://youtu.be/LeBufOOA9JM',
			date: '03.07.24',
			topic: 'Writing stories from one\'s life',
			social: 'https://www.authorjulietrose.com/',
			other: 'https://twitter.com/julietrosewords',
		},
		{ episode: '014', 
			guest: 'Ken and Bill',
			link: 'https://youtu.be/FIb6vow42dg',
			date: '03.14.24',
			topic: 'Propaganda and getting Cancelled',
			social: 'https://twitter.com/geekygamerpod',
			other: 'https://youtube.com/dreadloresystem',
		},
		{ episode: '015', 
			guest: 'Jed Shaffer',
			link: 'https://youtu.be/jl02XT-Nj_s',
			date: '03.21.24',
			topic: 'The Generations of Gaming Consoles',
			social: 'https://lnns.co/EjwO-T5Xe6_',
			other: '',
		},
		{ episode: '016', 
			guest: 'Tawd Dorenfeld',
			link: 'https://youtu.be/X-7-WtAzSmY',
			date: '03.28.24',
			topic: 'Stop motion, A.I., and Andy Warhol',
			social: 'https://www.instagram.com/directordorenfeld/',
			other: '',
		},
		{ episode: '017', 
			guest: 'Ali Khamseh',
			link: 'https://youtu.be/DZjmCSX6Fgo',
			date: '04.04.24',
			topic: 'Film-making in Iran',
			social: 'https://www.youtube.com/channel/UCP37QXeEcOQ5vJpQKgnph1w',
			other: '',
		},
		{ episode: '018', 
			guest: 'Danny Whitson',
			link: 'https://youtu.be/70j3m-HoLtU',
			date: '04.11.24',
			topic: 'Comedy and Magic',
			social: 'https://dannywhitsonmagic.com',
			other: 'https://www.youtube.com/channel/UCfFPSTU5x2AOKvSU1_4y4XA',
		},
		{ episode: '019', 
			guest: 'Tyler Foley',
			link: 'https://youtu.be/xmx-CS3aREk',
			date: '04.18.24',
			topic: 'Doing what you love',
			social: 'https://twitter.com/DropTheMicSTF',
			other: 'https://seantylerfoley.com',
		},
		{ episode: '020', 
			guest: 'Ben Rock',
			link: 'https://youtu.be/lrnTENqkI4Y',
			date: '04.19.24',
			topic: 'Co-creator of The Blair Witch Project',
			social:	'https://twitter.com/Neptunesalad',
			other: 'https://linktr.ee/neptunesalad',
		},
		{ episode: '021',
			guest: 'Lucas Zellers',
			link: 'https://youtu.be/9otJLN4qDLo',
			date: '04.25.24',
			topic: 'Creating & gaming with a goal in mind',
			social: 'https://twitter.com/SparkOtter',
			other: 'https://scintilla.studio/',
		},
		{ episode: '022', 
			guest: 'Ken and Bill',
			link: 'https://youtu.be/fzIDwsc8fTo',
			date: '05.02.24',
			topic: 'Fallout Spoilers, D&D sucks, ST Tangirala BAILED',
			social: 'https://twitter.com/geekygamerpod',
			other: 'https://youtube.com/dreadloresystem',
		},
		{ episode: '023',  
			guest: 'JV Hilliard',
			link: 'https://youtu.be/3-cctv9JBAk',
			date: '05.23.24',
			topic: 'The Warminster Series and Publishing',
			social: 'https://twitter.com/jvhilliardbooks',
			other: 'https://jvhilliard',
		},
		{ episode: '024',  
			guest: 'Constance Chamberlain',
			link: 'https://youtu.be/ikGiB8Ib0gI',
			date: '05.30.24',
			topic: 'LARPing, Renfaire, D&D, and everything geeky',
			social: '',
			other: '',
		},
		{ episode: '025',
			guest: 'Jason Sidwell',
			link: 'https://youtu.be/ktyaErJr0O0',
			date: '06.06.24',
			topic: 'Comic art, storytelling',
			social: 'https://twitter.com/jsidwell0',
			other: 'https://deviantart.com/jsidwell0',
		},
		{ episode: '026',
			guest: 'Faith McQuinn',
			link: 'https://youtu.be/S1hVnqmAg8E',
			date: '06.13.24',
			topic: 'Writing, directing, podcasting',
			social: 'https://twitter.com/observerpix',
			other: 'https://www.observerpictures.com',
		},
	];
	return guest_info;
}

export default GuestInfo; 

